version: "3.9"

services:
  mentorpark:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_COMMIT: "HEAD"
    container_name: mentorpark-app
    ports:
      - "9090:80"
    environment:
      APP_ENV: production
    restart: unless-stopped
